name: Docker Image CI

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD

      - name: Build the Docker image
        env:
            DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t seejnn/grabit -f server/Dockerfile server
        
        
          
      - name: taging
        run: docker tag seejnn/grabit minsuje/grabit
      - name: Push to Dockerhub
        run: docker push seejnn/grabit

