name: Docker Image CI

on:
    push:
        branches: ['develop']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Login to DockerHub
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
              run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

            - name: Build the Docker image
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
              run: |
                  docker build \
                    --build-arg DATABASE_URL=${DATABASE_URL} \
                    --build-arg JWT_SECRET_KEY=${JWT_SECRET_KEY} \
                    --build-arg TZ=Asia/Seoul \
                    -t seejnn/grabit -f server/Dockerfile server

            - name: Tagging
              run: docker tag seejnn/grabit minsuje/grabit

            - name: Push to DockerHub
              run: docker push seejnn/grabit
