name: Docker Image CI

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t minsuje/grabit -f server/Dockerfile server
      - name: taging
        run: docker tag grabit:latest minsuje/grabit:latest
      - name: Push to Dockerhub
        run: docker push minsuje/grabit:latest
